import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { WholeWord, CloudMoon } from "lucide-react";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import { ThemeProvider } from "@/features/themes/ui/theme-provider";
import { ToggleThemeBtn } from "@/features/themes/ui/toggle-btn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex flex-col grow min-h-screen"><ThemeProvider>
            <header className="flex justify-between border-b border-b-zinc-400 items-center p-4 h-16 dark:text-zinc-300 dark:bg-black">
              <Link href="/" className="flex items-center gap-4">
                <WholeWord />
                <h2 className="text-lg font-bold leading-tight tracking-[-0.015em]">
                  Voice2Words
                </h2>
              </Link>
              <div className="gap-4 flex">
                <Link href="/pricing">Pricing</Link>
                <SignedOut>
                  <SignInButton />
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Sign Up
                    </button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <Link href="/dashboard">Dashboard</Link>
                  <ToggleThemeBtn />
                  <UserButton />
                </SignedIn>
              </div>
            </header>
            {children}
          </ThemeProvider></div>
          <footer className="flex justify-center">
            <div className="flex max-w-[960px] flex-1 flex-col">
              <footer className="flex flex-col gap-6 px-5 py-10 text-center @container">
                <div className="flex flex-wrap items-center justify-center gap-6 @[480px]:flex-row @[480px]:justify-around">
                  <a className="text-neutral-500 text-base font-normal leading-normal min-w-40" href="#">Terms of Service</a>
                  <a className="text-neutral-500 text-base font-normal leading-normal min-w-40" href="#">Privacy Policy</a>
                  <a className="text-neutral-500 text-base font-normal leading-normal min-w-40" href="#">Contact Us</a>
                </div>
                <p className="text-neutral-500 text-base font-normal leading-normal">2025 Voice2Words. All rights reserved.</p>
              </footer>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
