import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { WholeWord, CloudMoon } from "lucide-react";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import { ThemeProvider } from "@/features/themes/ui/theme-provider";
import { ToggleThemeBtn } from "@/features/themes/ui/toggle-btn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider>
            <header className="flex justify-between border-b border-b-zinc-400 items-center p-4 h-16 dark:text-zinc-300 dark:bg-black">
              <div className="flex items-center gap-4">
                <WholeWord />
                <h2 className="text-lg font-bold leading-tight tracking-[-0.015em]">
                  Voice2Words
                </h2>
              </div>
              <div className="gap-4 flex">
                <Link href="/pricing">Pricing</Link>
                <SignedOut>
                  <SignInButton />
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Sign Up
                    </button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <Link href="/dashboard">Dashboard</Link>
                  <ToggleThemeBtn />
                  <UserButton />
                </SignedIn>
              </div>
            </header>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
